name: ftl
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - comm=0.2.3
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnsl=2.0.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.0.18
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - accelerate==0.26.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - bitsandbytes==0.42.0
      - blis==1.3.0
      - catalogue==2.0.10
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cloudpathlib==0.23.0
      - confection==0.1.5
      - cymem==2.0.11
      - datasets==2.16.1
      - dill==0.3.7
      - docstring-parser==0.17.0
      - en-core-web-sm==3.8.0
      - filelock==3.20.0
      - frozenlist==1.8.0
      - fsspec==2023.10.0
      - grpcio==1.76.0
      - hf-xet==1.2.0
      - huggingface-hub==0.20.3
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - langcodes==3.5.0
      - language-data==1.3.0
      - marisa-trie==1.3.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.15
      - murmurhash==1.0.13
      - networkx==3.4.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - pandas==2.3.3
      - peft==0.7.2.dev0
      - pillow==12.0.0
      - pipdeptree==2.29.0
      - preshed==3.0.10
      - propcache==0.4.1
      - protobuf==6.33.0
      - psutil==7.1.3
      - pyarrow==22.0.0
      - pyarrow-hotfix==0.7
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentence-transformers==2.6.1
      - shellingham==1.5.4
      - shtab==1.7.2
      - smart-open==7.4.3
      - spacy==3.8.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - thinc==8.3.6
      - threadpoolctl==3.6.0
      - tokenizers==0.15.2
      - torch==2.5.1+cu121
      - tqdm==4.67.1
      - transformers==4.36.2
      - triton==3.1.0
      - trl==0.7.11.dev0
      - typeguard==4.4.4
      - typer==0.20.0
      - typing-inspection==0.4.2
      - tyro==0.9.35
      - tzdata==2025.2
      - urllib3==2.5.0
      - wasabi==1.1.3
      - weasel==0.4.1
      - werkzeug==3.1.3
      - wrapt==2.0.0
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /home/zhenglon/miniconda3/envs/ftl
